In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import sys
!{sys.executable} -m pip install numpy

In [5]:
import numpy as np
print(np.__version__)

2.4.2


In [6]:
import numpy as np
arr = np.array([5, 10, 15, 20, 25, 30])
print(arr

[ 5 10 15 20 25 30]


In [7]:
import numpy as np
arr = np.array([5, 10, 15, 20, 25, 30])
print(arr [0])

5


In [8]:
import numpy as np
arr = np.array([5, 10, 15, 20, 25, 30])
print(arr [2])

15


In [9]:
import numpy as np
arr = np.array([5, 10, 15, 20, 25, 30])
print(arr [-1])

30


In [10]:
import numpy as np
arr = np.array([5, 10, 15, 20, 25, 30])
print(arr [1:4])

[10 15 20]


In [17]:
import numpy as np
arr = np.array([5, 10, 15, 20, 25, 30])
print(arr [4:6])

[25 30]


In [20]:
arr = np.array([2, 4, 6, 8, 10, 12, 14, 16])
print(arr)

[ 2  4  6  8 10 12 14 16]


In [27]:
arr = np.array([2, 4, 6, 8, 10, 12, 14, 16])
print(arr [0:4])

[2 4 6 8]


In [24]:
arr = np.array([2, 4, 6, 8, 10, 12, 14, 16])
print(arr [2:9])

[ 6  8 10 12 14 16]


In [28]:
arr = np.array([2, 4, 6, 8, 10, 12, 14, 16])
print(arr [::2])

[ 2  6 10 14]


In [29]:
arr = np.array([2, 4, 6, 8, 10, 12, 14, 16])
print(arr [::-1])

[16 14 12 10  8  6  4  2]


In [31]:
arr = np.array([2, 4, 6, 8, 10, 12, 14, 16])
print(arr [2: 6])

[ 6  8 10 12]


In [33]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr [0, 1])

2


In [35]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr [2, 1])

8


In [38]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr [1,2])

6


In [39]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr [0])

[1 2 3]


In [40]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr [2])

[7 8 9]


In [44]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr [:,1])

[20 50 80]


In [45]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr [:,0])

[10 40 70]


In [48]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr [0:2])

[[10 20 30]
 [40 50 60]]


In [51]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr [1:3])

[[40 50 60]
 [70 80 90]]


In [52]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr [:2, :2])

[[10 20]
 [40 50]]
